### PR TITLE
Initial hw2 for Gokul Puthumanaillam (gokulp2)

### PR DESCRIPTION
**Pull request by gokulp01**
To Do
- [ ] Code for plotting
- [ ] Better hyperparameter tuning

### CODE REVIEW

**Comment by Krith22** [comment]
Hi Gokul, I will review your code

**Comment by Krith22** [comment]
Overall the code looks great, I would add the code for plots

**Comment by Krith22** [comment]
Add the comments to the important parts of the code

**Comment by gokulp01** [comment]
Hi Krith, thank you for your comments. I have updated my code after incorporating your reviews.

**Pull request merged**
